clear csvfiles
clear csvfolders
clear csvPath
clear file_numCols
clear filefolders
clear filenames
clear files
clear myfiles
clear temp_Blockwise_Responses
clear file_numRows
clear fileTable
clear path
clear presentHeader
clear blockNum
clear lineNum
clear colNum
clear lineIdx_presentHeader
clear i
clear j
clear k
clear l
clear m
clear totalTime
clear totalConfidence
clear num_CorrectResponses_BLOCK
clear num_CorrectResponses_TOTAL
clear correctClasses_PROTO
clear choiceHeader
clear num_Files
clear participantIdx
clear correctClasses
clear med_OMSI
clear blockwise_Responses_Vector
clear blockwise_Responses_Matrix
clear C_temp
clear Tensor_Response
clear Tensor_Confidence
clear Tensor_ResponseTime
clear forCorr_AGG
clear forCorr_Conf_Vec
clear forCorr_Time_Vec
clear blockwise_ConfPerc_Matrix
clear blockwise_ConfPerc_Vector
clear blockwise_RespTime_Matrix
clear blockwise_RespTime_Vector
clear CORRECT_ConfPerc_VECTOR
clear CORRECT_RespTime_VECTOR
clear WRONG_ConfPerc_VECTOR
clear temp_Blockwise_ConfPerc
clear temp_Blockwise_RespTime
clear WRONG_ConfPerc_VECTOR
clear WRONG_RespTime_VECTOR
clear num_CorResp_TOTAL_REP
clear ALL_ConfPerc_VECTOR
clear ALL_CorrectClasses_VECTOR
clear ALL_Responses_VECTOR
clear ALL_RespTime_VECTOR
clear ALL_RightWrong_VECTOR
clear labels
clear num_CorResp_Blk_REP;